### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by alexvandervegt** [Geexteam/mollie-ES6#1]
Hi,

First of all nice wrapper!

However after installing and testing I get the following error:

`XMLHttpRequest cannot load https://api.mollie.nl/v1/payments. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.`

I see you are relaying on the `superagent` module, I found a ticket regarding this error on it:
https://github.com/visionmedia/superagent/issues/501

**Comment by Geex-Renzo** [comment]
Thank you!
Am I correct in assuming you're using the module from the browser using Browserify?
And I'll start looking in to it!

**Comment by alexvandervegt** [comment]
I use it in with webpack2

**Comment by alexvandervegt** [comment]
Maybe this is interesting to?

https://help.mollie.com/hc/nl/articles/214017905-Als-ik-de-Mollie-API-aanroep-via-AJAX-krijg-ik-de-foutmelding-No-Access-Control-Allow-Origin-header-is-present-

**Comment by Geex-Renzo** [comment]
Yes, it is.
So, it's not `allowed` to use the API on the front-end, which means you'll have to install it on a server instead.
Does that resolve this issue?

**Comment by alexvandervegt** [comment]
I dont know what you mean exactly? I use the function like in your example?

**Comment by Geex-Renzo** [comment]
Mollie does not allow you to create payments (etc.) from the front-end of a website, so this "issue" is a problem for this package.
To get it working, you'll have to install (`npm install --save mollie-es6`) on the application server, instead of using it with webpack to build a front-end.
You'll probably be able to 'copy-paste' the implementation of the package though ;)

**Comment by alexvandervegt** [comment]
ah! i understand, thanks for clearing!
